#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for pgxc/shard
#
# IDENTIFICATION
#    src/backend/pgxc/shard/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/pgxc/shard
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = shardmap.o shardbarrier.o shard_vacuum.o

include $(top_srcdir)/src/backend/common.mk
