#-------------------------------------------------------------------------
#
# Makefile for backend/audit
#
# src/backend/audit/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/audit
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = audit.o audit_fga.o

include $(top_srcdir)/src/backend/common.mk