#
# Makefile for the access methods module
#
# src/backend/access/Makefile
#

subdir = src/backend/contrib
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS	    = pgcrypto sm

include $(top_srcdir)/src/backend/common.mk
