#-------------------------------------------------------------------------
#
# Makefile for backend/oracle
#
# src/backend/oracle/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/oracle
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = others.o datefce.o plvstr.o convert.o charpad.o 

include $(top_srcdir)/src/backend/common.mk